### ISSUE TITLE
shared error

### ISSUE THREAD

**Issue by wormen** [CodeDredd/pinia-orm#1135]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `telemetry`, `runtimeConfig`, `app`, `typescript`, `modules`, `lodash`, `components`, `imports`, `alias`, `build`, `css`, `vite`
- Runtime Modules:  `@pinia/nuxt@0.4.7`, `@pinia-orm/nuxt@1.6.5`, `@vueuse/nuxt@9.13.0`, `nuxt-lodash@2.4.1`
- Build Modules:    `-`
------------------------------

### Reproduction

the error appeared after the update, and continues to appear since version 1.6.1
in version 1.5.1 there is no such error

### Describe the bug

appears when the application is launched in dev mode, I did not even try to build

### Logs

```shell
ERROR  Error while requiring module @pinia-orm/nuxt: Error: Cannot find module './shared/pinia-orm.34b622d8.cjs'
 Require stack:
 - /app/node_modules/pinia-orm/dist/index.js
  
  ERROR  Cannot start nuxt:  Cannot find module './shared/pinia-orm.34b622d8.cjs'
 Require stack:
 - /app/node_modules/pinia-orm/dist/index.js
 
   Require stack:
   - node_modules/pinia-orm/dist/index.js
   at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
   at Function.resolve (node:internal/modules/cjs/helpers:116:19)
   at _resolve (node_modules/jiti/dist/jiti.js:1:241025)
   at jiti (node_modules/jiti/dist/jiti.js:1:243309)
   at node_modules/pinia-orm/dist/index.js:3:15
   at jiti (node_modules/jiti/dist/jiti.js:1:245784)
   at node_modules/@pinia-orm/nuxt/dist/module.cjs:4:18
   at jiti (node_modules/jiti/dist/jiti.js:1:245784)
   at requireModule (node_modules/@nuxt/kit/dist/index.mjs:286:26)
   at normalizeModule (node_modules/@nuxt/kit/dist/index.mjs:472:77)
```
```

**Comment by CodeDredd** [comment]
@wormen Please try v1.6.6. Should be working now

**Comment by wormen** [comment]
@CodeDredd unfortunately still the same error, no change

**Comment by CodeDredd** [comment]
@wormen now....finally found it. v1.6.7 is doing the trick

**Comment by wormen** [comment]
@CodeDredd 
now everything works without errors
thank you for the promptness))
