### ISSUE TITLE
main.js:42 Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@pinia-orm_axios.js?v=40365b2e' does not provide an export named 'createPiniaOrmPluginAxios' (at main.js:42:10)

### ISSUE THREAD

**Issue by ivanswoop006** [CodeDredd/pinia-orm#1777]
### Environment

vue 2

### Reproduction

put this code in main file

```
import { createPinia, PiniaVuePlugin } from 'pinia'
import { createORM } from 'pinia-orm'
import { createPiniaOrmPluginAxios } from '@pinia-orm/axios'

Vue.use(PiniaVuePlugin)
const pinia = createPinia()
const piniaOrm = createORM()
piniaOrm().use(createPiniaOrmPluginAxios({
  axios
}))
pinia.use(piniaOrm)
```

### Describe the bug

main.js:42 Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@pinia-orm_axios.js?v=40365b2e' does not provide an export named 'createPiniaOrmPluginAxios' (at main.js:42:10)

### Logs

```shell
main.js:42 Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@pinia-orm_axios.js?v=40365b2e' does not provide an export named 'createPiniaOrmPluginAxios' (at main.js:42:10)
```

**Comment by ivanswoop006** [comment]
maybe its meant to be "createPiniaOrmAxios" not  "createPiniaOrmPluginAxios"

**Comment by CodeDredd** [comment]
@ivanswoop006 you are right. My mistake in the docs 😞
