### ISSUE TITLE
hasManyBy for Many To Many?

### ISSUE THREAD

**Issue by salcedo** [CodeDredd/pinia-orm#378]
### Describe the feature

I have a backend with contact and contact emails that get serialized out like this:

a contact:
```json
{
  "id": 1,
  "name": "Wanda",
  "emails": [
    {
      "id": 10,
      "contact_ids": [1],
      "email_address": "wanda@wanda.com"
    }
  ]
}
```

On the backend, these models are related many-to-many. There should be a way for pinia-orm to be able to save either a contact or contact email and have the relationships work even when the backend data coming in is an array of ids instead of a serialized object, similar to hasManyBy but works with a pivot table.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Check existing [discussions](https://github.com/CodeDredd/pinia-orm/discussions) and [issues](https://github.com/CodeDredd/pinia-orm/issues).

**Comment by salcedo** [comment]
During a phase where we moved our application from vuex to pinia, prior to pinia-orm existing, I ended up writing a crude ORM to hold us over. I ran into a challenge where, if the backend sent one side of a relationship that only had an array of ids for the related objects, and those related objects did not yet exist in the store. My solution was to save the related objects in the store with only an id property (with the expectation that we'd need to fetch those relationships later). While not ideal, it was the best I could come up with and would have to check in certain situations if an object only had an id property with no other fields.

**Comment by CodeDredd** [comment]
Hmm i am not sure if i get your point. From my point it should be possible to save only `ids` without the relations being in store. 
Can you give a bit more information about the relations between the models and maybe an example what pinia-orm doesn't do what you need?

**Comment by salcedo** [comment]
I have models set up like this:

```javascript
export class Contact extends Model {
  static fields() {
    return {
      id: this.uid(),
      name: this.string(""),
      emails: this.belongsToMany(
        ContactEmail,
        ContactEmailContact,
        "contactId",
        "contactEmailId"
      ),
    };
  }
}
Contact.entity = "contacts";

export class ContactEmail extends Model {
  static fields() {
    return {
      id: this.uid(),
      email_address: this.string(""),
      contacts: this.belongsToMany(
        Contact,
        ContactEmailContact,
        "contactEmailId",
        "contactId"
      ),
    };
  }
}
ContactEmail.entity = "contact_emails";

class ContactEmailContact extends Model {
  static fields() {
    return {
      contactEmailId: this.uid(),
      contactId: this.uid(),
    };
  }
}
ContactEmailContact.entity = "contact_email_contact";
ContactEmailContact.primaryKey = ["contactEmailId", "contactId"];
```

The backend sends contacts like this:

```json
[
        {
            "id": 1,
            "emails": [
                {
                    "id": 10,
                    "contacts": [
                        1
                    ],
                    "email_address": "wanda@wanda.com",
                }
            ],
            "name": "Wanda",
        }
]
```

The backend sends contact emails like this:

```json
[
        {
            "id": 10,
            "contacts": [
                1
            ],
            "email_address": "wanda@wanda.com",
        }
]
```

belongsToMany is expecting an array of objects and throws this error when it sees the array of ids from contact emails:

```
pinia-orm.c0f71df4.mjs:95 Uncaught (in promise) Error: [Pinia ORM] The record is missing the primary key. If you want to persist record without the primary key, please define the primary key field with the `uid` attribute.
    at throwError (pinia-orm.c0f71df4.mjs:95:9)
    at assert (pinia-orm.c0f71df4.mjs:99:5)
    at Contact.$getIndexId (index.mjs:1652:5)
    at Query.reviveOne (index.mjs:570:27)
    at index.mjs:580:26
    at Array.reduce (<anonymous>)
    at Query.reviveMany (index.mjs:579:19)
    at Query.reviveRelations (index.mjs:599:76)
    at Query.reviveOne (index.mjs:575:10)
    at index.mjs:580:26
```

**Comment by CodeDredd** [comment]
Ok now i know what you need.
What about this solution ?
````js
export class Contact extends Model {
  static fields() {
    return {
      id: this.uid(),
      name: this.string(""),
      emails: this.belongsToMany(
        ContactEmail,
        ContactEmailContact,
        "contactId",
        "contactEmailId"
      ),
    };
  }
}
Contact.entity = "contacts";

export class ContactEmail extends Model {
  static fields() {
    return {
      id: this.uid(),
      email_address: this.string(""),
      contacts: this.attr([]),
      contactObject: this.hasManyBy(Contact, 'contacts')
    };
  }
}
ContactEmail.entity = "contact_emails";

class ContactEmailContact extends Model {
  static fields() {
    return {
      contactEmailId: this.uid(),
      contactId: this.uid(),
    };
  }
}
ContactEmailContact.entity = "contact_email_contact";
ContactEmailContact.primaryKey = ["contactEmailId", "contactId"];
````

**Comment by salcedo** [comment]
This solution does not work because adding or removing a ContactEmail (and saving the response via a repo for ContactEmail) does not update the ContactEmailContact pivot model.

Thus, a computed function such as this:
```javascript
    const contact = computed(() =>
      useRepo(ContactEmail).with("emails").first()
    );
```
will not see a new email that was added, requiring an application to re-fetch the contact from the backend to satisfy the belongsToMany relationship in Contact.

**Comment by CodeDredd** [comment]
What about this solution?

````js
export class Contact extends Model {
  static fields() {
    return {
      id: this.uid(),
      name: this.string(""),
      emails: this.belongsToMany(
        ContactEmail,
        ContactEmailContact,
        "contactId",
        "contactEmailId"
      ),
    };
  }
}
Contact.entity = "contacts";

export class ContactEmail extends Model {
  static fields() {
    return {
      id: this.uid(),
      email_address: this.string(""),
      contacts: this.attr([]),
      contactObjects: this.hasManyBy(Contact, 'contacts')
    };
  }
  static saving(model) {
    useRepo(ContactEmailContact).save(model.contacts.map(contactId => {
      contactEmailId: model.id,
      contactId: contactId
    }))
  }
  static deleting(model) {
    useRepo(ContactEmailContact)
    .whereIn('contactId', model.contact)
    .where('contactEmailId', model.id)
    .delete()
  }
}
ContactEmail.entity = "contact_emails";

class ContactEmailContact extends Model {
  static fields() {
    return {
      contactEmailId: this.uid(),
      contactId: this.uid(),
    };
  }
}
ContactEmailContact.entity = "contact_email_contact";
ContactEmailContact.primaryKey = ["contactEmailId", "contactId"];
````

**Comment by salcedo** [comment]
That'll do it. Thank you so much.
